export const LOAD_CAMPERS_SUCCESS = 'LOAD_COURSES';
export const SORT = 'SORT';
export const SORT_TYPES = {
  NAME_DESC: 'NAME_DESC',
  NAME_ASC: 'NAME_ASC',
  PAST_30_DESC: 'PAST_30_DESC',
  PAST_30_ASC: 'PAST_30_ASC',
  ALL_TIME_ASC: 'ALL_TIME_ASC',
  ALL_TIME_DESC: 'ALL_TIME_DESC'
}